// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TowaCinema.Server.Db.Context;

#nullable disable

namespace TowaCinema.Server.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20231118132132_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TowaCinema.Server.Db.DbModels.Completed", b =>
                {
                    b.Property<Guid>("StreamVideoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("StreamVideoId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Completed");
                });

            modelBuilder.Entity("TowaCinema.Server.Db.DbModels.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("TowaCinema.Server.Db.DbModels.InProgress", b =>
                {
                    b.Property<Guid>("StreamVideoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StopTimeInSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("StreamVideoId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("InProgress");
                });

            modelBuilder.Entity("TowaCinema.Server.Db.DbModels.StreamGame", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StreamVideoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameTimestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "StreamVideoId");

                    b.HasIndex("StreamVideoId");

                    b.ToTable("StreamGame");
                });

            modelBuilder.Entity("TowaCinema.Server.Db.DbModels.StreamVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StreamDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StreamVideos");
                });

            modelBuilder.Entity("TowaCinema.Server.Db.DbModels.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TowaCinema.Server.Db.DbModels.Completed", b =>
                {
                    b.HasOne("TowaCinema.Server.Db.DbModels.StreamVideo", "StreamVideo")
                        .WithMany("Completeds")
                        .HasForeignKey("StreamVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowaCinema.Server.Db.DbModels.User", "User")
                        .WithMany("Completeds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamVideo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TowaCinema.Server.Db.DbModels.InProgress", b =>
                {
                    b.HasOne("TowaCinema.Server.Db.DbModels.StreamVideo", "StreamVideo")
                        .WithMany("InProgresses")
                        .HasForeignKey("StreamVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowaCinema.Server.Db.DbModels.User", "User")
                        .WithMany("InProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamVideo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TowaCinema.Server.Db.DbModels.StreamGame", b =>
                {
                    b.HasOne("TowaCinema.Server.Db.DbModels.Game", "Game")
                        .WithMany("StreamGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowaCinema.Server.Db.DbModels.StreamVideo", "StreamVideo")
                        .WithMany("StreamGames")
                        .HasForeignKey("StreamVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("StreamVideo");
                });

            modelBuilder.Entity("TowaCinema.Server.Db.DbModels.Game", b =>
                {
                    b.Navigation("StreamGames");
                });

            modelBuilder.Entity("TowaCinema.Server.Db.DbModels.StreamVideo", b =>
                {
                    b.Navigation("Completeds");

                    b.Navigation("InProgresses");

                    b.Navigation("StreamGames");
                });

            modelBuilder.Entity("TowaCinema.Server.Db.DbModels.User", b =>
                {
                    b.Navigation("Completeds");

                    b.Navigation("InProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
